
services:
  guacd:
    container_name: guacamole-guacd
    image: guacamole/guacd
    user: 0:0 # optional: Set custom user/group or uid/gid
    environment:   
      - "TZ=America/Los_Angeles"
    networks:
      frontend: 
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.5.20:1514"
        #syslog-format: "rfc3164"
        tag: "guacamole"
    restart: always

  postgres:
    container_name: guacamole-postgres
    user: 0:0 # optional: Set custom user/group or uid/gid
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      frontend: 
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.5.20:1514"
        #syslog-format: "rfc3164"
        tag: "guacamole-postgres"

  # guacamole
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole
    user: 0:0 # optional: Set custom user/group or uid/gid
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user

    links:
    - guacd
    networks:
      frontend: 
    ports:
      - 8686:8080/tcp
    restart: always
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.5.20:1514"
        #syslog-format: "rfc3164"
        tag: "guacamole"
networks:
  frontend:
    external: true
