# yamllint disable rule:line-length
---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

users:
  ecloaiza:
    disabled: false
    displayname: "Emmanuel Loaiza"
    password: "$argon2id$v=19$m=65536,t=3,p=4$C006JuettfO1mSS7TtUEkQ$xqHxN1koF4kWht6y65fnowH6fyJKbGdlQixouK9JZDs"  # Password is 'authelia'
    email: smarth@elikesbikes.com
    groups:
      - admins
      - dev  
  root:
    disabled: false
    displayname: "Test User"
    password: "$argon2id$v=19$m=65536,t=3,p=4$jVk23Br2J23wKzwD13MfkA$MgQf7hxwNKCCKA8VT+qQ6yAwm+qoZuZmWakOOl/Kzrc"  # Password is 'authelia'
    email: smarth@elikesbikes.com
    groups:
      - admins
      - dev
...
# yamllint enable rule:line-length
