version: "2.1"
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    hostname: ntfy
    command:
      - serve
    environment:   
      - "TZ=America/Los_Angeles"
    user: 0:0 # optional: Set custom user/group or uid/gid
    volumes:
      - ./cache/ntfy:/var/cache/ntfy
      - ./etc/ntfy:/etc/ntfy
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.5.20:1514"
        #syslog-format: "rfc3164"
        tag: "ntfy"
    ports:
      - 8989:80
    networks:
      frontend: 
    restart: unless-stopped
networks:
  frontend:
    external: true
