---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "ELIKESBIKES"
subtitle: "Home Lab"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
#message:
#  #url: https://b4bz.io
#  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Network"
    icon: "fa-sharp fa-solid fa-network-wired"
    items:
      - name: "Ubiquiti"      
        logo: "assets/icons/ui.png"
        subtitle: "Router"
        tag: "app"
        keywords: "Ubiquiti UDM"
        url: "https://emiudm.home.elikesbikes.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Revise Proxy"      
        logo: "assets/icons/nginx.jpg"
        subtitle: "Proxy"
        tag: "app"
        keywords: "NGINX"
        url: "https://proxy.home.elikesbikes.com/"
        target: "_blank" # optional html a tag target attribute


  - name: "Server"
    icon: "fa-solid fa-server"
    items:
      - name: "emihpvproxmox1"
        logo: "assets/icons/proxmox.png"
        subtitle: "Virtual Machine Management"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://hpv1.home.elikesbikes.com"
        target: "_blank" # optional html a tag target attribute
      - name: "emihpvproxmox2"                                 
        logo: "assets/icons/proxmox.png"                        
        subtitle: "Virtual Machine Management"                                 
        tag: "app"                                             
        keywords: "self hosted reddit"                         
        url: "https://hpv1.home.elikesbikes.com"                      
        target: "_blank" # optional html a tag target attribute 
      - name: "emihpvproxmox3"                                 
        logo: "assets/icons/proxmox.png"                        
        subtitle: "Virtual Machine Management"                                 
        tag: "app"                                             
        keywords: "self hosted reddit"                         
        url: "https://hpv3.home.elikesbikes.com"                      
        target: "_blank" # optional html a tag target attribute 


      - name: "Truenas Scale"
        logo: "assets/icons/truenas.png"
        subtitle: "NAS Storage"
        tag: "NAS"
        url: "https://nas.home.elikesbikes.com"


  - name: "Monitoring"
    icon: "fa-brands fa-watchman-monitoring"
    items:
      - name: "Prometheous"
        #logo: "assets/icons/observium.jpeg"
        subtitle: "Monitoring"
        tag: "app"
        keywords: "self hosted reddit"
        url: "http://192.168.5.20:9090/targets?search="
        target: "_blank" # optional html a tag target attribute
      - name: "Linode - Uptime Kuma"
        logo: "assets/icons/uptimakuma.png"
        subtitle: "Monitoring WAN"
        tag: "app"
        keywords: "self hosted reddit"
        url: "http://96.126.97.197"
        target: "_blank" # optional html a tag target attribute
      - name: "Home Network - Uptime Kuma"
        logo: "assets/icons/uptimakuma.png"
        subtitle: "Monitoring WAN"
        tag: "app"
        keywords: "self hosted reddit"
        url: "http://uptimenas.home.elikesbikes.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Graylog"                                 
        logo: "assets/icons/graylog.png"                        
        subtitle: "Graylog Server"                                 
        tag: "app"                                             
        keywords: "self hosted reddit"                         
        url: "https://graylog.home.elikesbikes.com"                      
        target: "_blank" # optional html a tag target attribute 
      - name: "Zabbix Monitoring"                                 
        logo: "assets/icons/zabbix_logo_500x131.png"                        
        subtitle: "Monitoring Server"                                 
        tag: "app"                                             
        keywords: "self hosted reddit"                         
        url: "http://192.168.5.20:8080"
        target: "_blank" # optional html a tag target attribute 


  - name: "Smart Home"
    icon: "fa-solid fa-house-signal"
    items:
      - name: "Home Assistant"      
        logo: "assets/icons/ha.png"
        subtitle: "Automation"
        tag: "app"
        keywords: "HA"
        url: "http://192.168.5.67:8123/"
        target: "_blank" # optional html a tag target attribute
      - name: "Sense Solar"
        logo: "assets/icons/sense.jpg"
        subtitle: "Solar Panels"
        tag: "sense"
        url: "https://home.sense.com/login"


  - name: "Applications"
    icon: "fa-solid fa-house-signal"
    items:
      - name: "Portainer"      
        logo: "assets/icons/portainer.png"
        subtitle: "Automation"
        tag: "app"
        keywords: "portainer"
        url: "https://docker.home.elikesbikes.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Blueiris"
        logo: "assets/icons/blueiris.jpeg"
        subtitle: "Security Cameras"
        tag: "sense"
        url: "https://security.home.elikesbikes.com"
      - name: "Teleport"
        logo: "assets/icons/Teleport.jpg"
        subtitle: "SSH"
        tag: "sense"
        url: "https://teleport.home.elikesbikes.com:3080"
      - name: "Ntfy"
        logo: "assets/icons/Teleport.jpg"
        subtitle: "notify"
        tag: "alerts"
        url: "https://ntfy.home.elikesbikes.com/uptimenasprod"
  

  - name: "Docker"
    icon: "fa-brands fa-docker"
    items:
      - name: "Grafana"      
        logo: "assets/icons/grafana.png"
        subtitle: "Automation"
        tag: "app"
        keywords: "portainer"
        url: "https://grafana.home.elikesbikes.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Influxdb"
        logo: "assets/icons/influxdb.png"
        subtitle: "Database"
        tag: "db"
        url: "https://db.home.elikesbikes.com"
      - name: "Nextcloud"
        logo: "assets/icons/Nextcloud_Logo.svg.png"
        subtitle: "File Storage"
        tag: "db"
        url: "https://nextcloud.home.elikesbikes.com/"


  - name: "Cloud"
    icon: "fa-regular fa-cloud"
    items:
      - name: "Cloudflare"      
        logo: "assets/icons/Cloudflare_Logo.svg.png "
        subtitle: "DNS Management"
        tag: "dns"
        keywords: "dns"
        url: "https://dash.cloudflare.com"
        target: "_blank" # optional html a tag target attribute

      - name: "Zoho Email"
        logo: "assets/icons/Zoho-Mail.png"
        subtitle: "Email Hosting"
        tag: "email"
        url: "https://mailadmin.zoho.com/cpanel/"

      - name: "Linode"
        logo: "assets/icons/linode-white.png "
        subtitle: "Virtual Data Center"
        tag: "cloud"
        url: "https://cloud.linode.com/linodes"
