version: '3.9'
networks:
  frontend:
    external: true
services:
  wyl:
    image: aceberg/watchyourlan
    container_name: watchyourlan
    hostname: watchyourlan
    network_mode: "host"        
    restart: unless-stopped
    volumes:
    - ~/.dockerdata/wyl:/data
    logging:
      driver: syslog
      options:
        syslog-address: "udp://192.168.5.20:1514"
        #syslog-format: "rfc3164"
        tag: "watchyourlan"
    environment:
      - "TZ=America/Los_Angeles"        # required: needs your TZ for correct time
      IFACE: "virbr-bw wlxf4ec3892dd51" # required: 1 or more interface
      DBPATH: "/data/db.sqlite"         # optional, default: /data/db.sqlite
      GUIIP: "0.0.0.0"                  # optional, default: localhost
      GUIPORT: "8840"                   # optional, default: 8840
      TIMEOUT: "120"                    # optional, time in seconds, default: 60
      SHOUTRRR_URL: ""                  # optional, set url to notify
      THEME: "darkly"                   # optional
      IGNOREIP: "no"                    # optional