version: '2'

networks:
  frontend:
    driver: bridge

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    hostname: emidocknextcloud-db.emi.dock
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=602043297 #change this
      - MYSQL_PASSWORD=60204397 #change this
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - frontend
 
  app:
    image: nextcloud
    hostname: emidocknextcloud-app.emi.dock
    restart: always
    ports:
      - 8888:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=60204397  #change this to match the mysql_password above
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=emidocknextcloud-db.emi.dock
    networks:
      - frontend